services:
  streamlit-visualization:
    image: ${DOCKER_USERNAME}/${DOCKER_PREFIX}-streamlit-visualization:${TAG}
    ports:
      - "8501:8501"
    env_file:
      - .env
    networks:
      - app-network

  backend:
    image: ${DOCKER_USERNAME}/${DOCKER_PREFIX}-backend:${TAG}
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - app-network

  telegram-bot:
    image: ${DOCKER_USERNAME}/${DOCKER_PREFIX}-telegram-bot:${TAG}
    env_file:
      - .env
    networks:
      - app-network
    restart: always

  postgres:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: prod
      POSTGRES_PASSWORD: prod
      POSTGRES_DB: prod 
    networks:
      - app-network
    ports:
      - "5432:5432"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: