services:
  streamlit-visualization:
    image: ${DOCKER_USERNAME}/${DOCKER_PREFIX}-streamlit-visualization:${TAG}
    ports:
      - "8501:8501"
    env_file:
      - .env
    networks:
      - app-network

  backend:
    image: ${DOCKER_USERNAME}/${DOCKER_PREFIX}-backend:${TAG}
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - app-network

  telegram-bot:
    image: ${DOCKER_USERNAME}/${DOCKER_PREFIX}-telegram-bot:${TAG}
    env_file:
      - .env
    networks:
      - app-network
    restart: always

  redis:
    image: redis:7
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USER: ${REDIS_USER}
      REDIS_USER_PASSWORD: ${REDIS_USER_PASSWORD}
    networks:
      - app-network
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_USER}
    networks:
      - app-network
    ports:
      - "5432:5432"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: