# Сокращённый CI/CD
# Используется для быстрого деплоя на сервер
# Без тестирования и сборки контейнеров

on:
    push:
        branches: [] # Не используется сейчас


jobs:
    job-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        # Подключение к машине
        - name: Clone repo
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            script: |
              mkdir -p /root/${{ vars.DOCKER_CI_TAG }}
              cd /root/${{ vars.DOCKER_CI_TAG }}

              # Если нет репозитория, копируем его с docker-compose и .env.example
              if [ ! -d ".git" ]; then
                git clone https://${{ secrets.GHP_PAT }}@github.com/${{ github.repository }} .
              else
                git fetch origin
                git reset --hard origin/master
              fi

              # Создаём .env из .env.example
              if [ ! -f .env ]; then
                cp .env.example .env
              fi

        - name: Run docker-compose
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            script: |
              cd /root/${{ vars.DOCKER_CI_TAG }}
              docker compose up -d --build