on:
    push:
        branches: [master]

# Собираем всё подряд -> Пушим в <branch-name>-develop
# Делаем пулл, тестируем, если тесты прошли -> пушим в <branch-name>-deploy
# Делаем деплой на сервер с последними валидными контейнерами

jobs:
    # Билдим всё подряд
    job-build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            # Сервисы приложения
            service:
              - backend
              - telegram-bot
              - streamlit-visualization
            include:
              - service: backend
                dockerfile: ./backend/Dockerfile
                context: ./backend
                
              - service: telegram-bot
                dockerfile: ./telegram-bot/Dockerfile
                context: ./telegram-bot

              - service: streamlit-visualization
                dockerfile: ./streamlit-visualization/Dockerfile
                context: ./streamlit-visualization

        steps:
          # Для получения кода в джобе
          - name: Checkout code.
            uses: actions/checkout@v4

          - name: Docker login
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_TOKEN }}

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2

          # Билдим и пушим в регистри
          - name: Docker build and push ${{ matrix.service }}
            uses: docker/build-push-action@v3
            with:
              context: ${{ matrix.context }}
              dockerfile: ${{ matrix.dockerfile }}
              push: True

              # Отправляем в девелоп
              tags: |
                ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:develop
                ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:develop-${{ github.sha }}

    job-test:
        needs: job-build
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code.
            uses: actions/checkout@v4

          - name: Run tests.
            run: echo Running tests...
           
    job-deploy:
        needs:
          - job-test
          - job-build
        runs-on: ubuntu-latest
        steps:
          - name: Deploy service.
            run: echo Deploying...

    job-ok:
        needs:
          - job-deploy
        runs-on: ubuntu-latest
        steps:
          - name: Check.
            run: echo i am fine