on:
    push:
        branches: [master]

jobs:
    test-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code.
              uses: actions/checkout@v4

            - name: Some test.
              run: echo Test!
