on:
    push:
        branches: [master]

# В CI тест и билд приложения
jobs:
    job-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code.
              uses: actions/checkout@v4

            - name: build mock
              run: echo Build mock!